"""Expectancy and the risk gates it drives — including data provenance.

The symbol kill-switch reads reports/backtests/latest_summary.json, which is
produced by an OFFLINE backtest and is never regenerated by live operation.
That provenance is the single most consequential fact on this page, so it is
displayed as a first-class warning rather than a footnote.
"""

from __future__ import annotations

from typing import Any

from dashboard_v3.core import sources as src
from dashboard_v3.core.status import Signal, SignalSet, Status

#: Thresholds mirrored from risk/risk_manager.py for DISPLAY ONLY.
#: This module never gates anything; it explains what the engine decided.
SYMBOL_MIN_TRADES = 3
STRATEGY_MIN_TRADES = 5


def _f(v: Any, d: float = 0.0) -> float:
    try:
        return float(v) if v not in (None, "") else d
    except (TypeError, ValueError):
        return d


def _symbol_verdict(stats: dict[str, Any]) -> tuple[str, Status, str]:
    trades = int(_f(stats.get("trades")))
    exp = _f(stats.get("expectancy"))
    lossrate = _f(stats.get("lossrate"))
    if trades < SYMBOL_MIN_TRADES:
        return ("INSUFFICIENT_DATA", Status.UNKNOWN,
                f"{trades} trades < {SYMBOL_MIN_TRADES} minimum — gate does not engage")
    if exp < 0:
        return ("PAUSED", Status.BLOCKED, f"expectancy {exp:+.4f} < 0")
    if trades >= 5 and lossrate >= 0.75:
        return ("PAUSED", Status.BLOCKED, f"loss rate {lossrate:.0%} >= 75%")
    return ("PASSES", Status.HEALTHY, f"expectancy {exp:+.4f}")


def build() -> dict[str, Any]:
    signals = SignalSet()

    strategy_loaded = src.load_json("reports/backtests/strategy_expectancy.json", default={})
    symbol_loaded = src.load_json("reports/backtests/latest_summary.json", default={})

    sdata = strategy_loaded.value if isinstance(strategy_loaded.value, dict) else {}
    ydata = symbol_loaded.value if isinstance(symbol_loaded.value, dict) else {}

    # --- strategies (live-maintained, rolling window) --------------------
    strategies = []
    for name, stats in (sdata.get("strategies") or {}).items():
        if not isinstance(stats, dict):
            continue
        exp = _f(stats.get("expectancy"))
        trades = int(_f(stats.get("trades")))
        fresh = stats.get("fresh_since_geometry_fix") or {}
        strategies.append({
            "name": name,
            "trades": trades,
            "winrate": _f(stats.get("winrate")),
            "expectancy": exp,
            "profit_factor": _f(stats.get("profit_factor")),
            "tp1_hit_rate": _f(stats.get("tp1_hit_rate")),
            "total_pnl": _f(stats.get("total_pnl")),
            "status": str(stats.get("status") or "UNKNOWN"),
            "gate_status": Status.BLOCKED if exp < 0 else Status.HEALTHY,
            "probe": exp < 0 and trades >= STRATEGY_MIN_TRADES,
            "fresh_expectancy": _f(fresh.get("expectancy")) if fresh else None,
            "fresh_trades": int(_f(fresh.get("trades"))) if fresh else None,
        })
    strategies.sort(key=lambda s: s["expectancy"])

    # --- symbols (STALE offline backtest) --------------------------------
    symbols = []
    for name, stats in (ydata.get("by_symbol") or {}).items():
        if not isinstance(stats, dict):
            continue
        verdict, status, reason = _symbol_verdict(stats)
        symbols.append({
            "symbol": name,
            "trades": int(_f(stats.get("trades"))),
            "winrate": _f(stats.get("winrate")),
            "lossrate": _f(stats.get("lossrate")),
            "expectancy": _f(stats.get("expectancy")),
            "tp1_hit_rate": _f(stats.get("tp1_hit_rate")),
            "pnl": _f(stats.get("pnl")),
            "verdict": verdict,
            "verdict_status": status,
            "reason": reason,
        })
    symbols.sort(key=lambda s: s["expectancy"], reverse=True)

    # --- provenance verdicts --------------------------------------------
    symbol_prov = symbol_loaded.provenance
    symbol_age_days = (symbol_prov.age_seconds or 0) / 86400.0
    symbol_stale = symbol_age_days > 2

    if not symbol_prov.exists:
        signals.add(Signal("symbol_data", "Symbol expectancy source", Status.UNKNOWN,
                           "latest_summary.json absent"))
    elif symbol_stale:
        signals.add(Signal(
            "symbol_data", "Symbol expectancy source", Status.BLOCKED,
            f"offline backtest, {symbol_age_days:.1f} days old",
            "This file is written only by scripts/run_backtest.py. Live trading "
            "never refreshes it, so a symbol paused here can never re-qualify.",
        ))
    else:
        signals.add(Signal("symbol_data", "Symbol expectancy source", Status.HEALTHY,
                           f"{symbol_prov.age_label} old"))

    if not strategy_loaded.provenance.exists:
        signals.add(Signal("strategy_data", "Strategy expectancy source", Status.UNKNOWN,
                           "strategy_expectancy.json absent"))
    else:
        signals.add(Signal("strategy_data", "Strategy expectancy source",
                           strategy_loaded.provenance.status,
                           f"{strategy_loaded.provenance.age_label} old · "
                           f"{sdata.get('expectancy_window_days', '?')}d rolling window"))

    paused_strategies = [s for s in strategies if s["status"] == "PAUSE"]
    if paused_strategies:
        signals.add(Signal(
            "strategy_pause", "Strategy gates", Status.BLOCKED,
            f"{len(paused_strategies)} of {len(strategies)} PAUSE",
            "PAUSE means negative expectancy; the engine trades these at probe size.",
        ))

    paused_symbols = [s for s in symbols if s["verdict"] == "PAUSED"]
    if paused_symbols:
        signals.add(Signal("symbol_pause", "Symbol gates", Status.BLOCKED,
                           f"{len(paused_symbols)} of {len(symbols)} PAUSED"))

    summary = sdata.get("summary") or {}
    recovery = sdata.get("recovery_events") or {}

    return {
        "signals": signals,
        "status": signals.status,
        "strategies": strategies,
        "symbols": symbols,
        "symbol_provenance": symbol_prov,
        "strategy_provenance": strategy_loaded.provenance,
        "symbol_stale": symbol_stale,
        "symbol_age_days": symbol_age_days,
        "window_days": sdata.get("expectancy_window_days"),
        "created_at": sdata.get("created_at_utc"),
        "symbol_created_at": ydata.get("created_at_utc"),
        "cohorts": {
            "strategy": summary.get("strategy") or {},
            "recovery": summary.get("recovery") or {},
            "all_closed": summary.get("all_closed") or {},
        },
        "recovery_events": [
            {"name": k, **{kk: v.get(kk) for kk in
                           ("trades", "winrate", "expectancy", "total_pnl", "status")}}
            for k, v in recovery.items() if isinstance(v, dict)
        ],
    }


__all__ = ["build"]
