#!/bin/bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

STATE_FILE="state/forward_paper_runtime.state"
if [ ! -f "$STATE_FILE" ]; then
  echo "status=NOT_STARTED"
  exit 1
fi

# The state file is generated by start_forward_paper.sh and contains only
# fixed keys with non-secret scalar values.
MODE="$(awk -F= '$1=="mode" {print $2}' "$STATE_FILE")"
PID="$(awk -F= '$1=="pid" {print $2}' "$STATE_FILE")"
INTERVAL="$(awk -F= '$1=="scan_interval_sec" {print $2}' "$STATE_FILE")"

if [ "$MODE" != "FORWARD_PAPER_ONLY" ]; then
  echo "status=INVALID_RUNTIME_MODE"
  exit 2
fi

if ! [[ "$PID" =~ ^[0-9]+$ ]] || ! ps -p "$PID" >/dev/null 2>&1; then
  echo "status=PROCESS_NOT_RUNNING"
  exit 3
fi

if ! ps -p "$PID" -o command= | grep -Eq "app\.main"; then
  echo "status=UNEXPECTED_PROCESS"
  exit 4
fi

if ! grep -Fq "FORWARD_PAPER_ONLY ACTIVE" logs/forward_paper.out 2>/dev/null \
  || ! grep -Fq "PRIVATE EXCHANGE CALLS DISABLED" logs/forward_paper.out 2>/dev/null; then
  echo "status=STRICT_MODE_MARKERS_MISSING"
  exit 5
fi

if grep -Eiq "Private API OK|PING_PRIVATE|GET_ACCOUNTS|get_all_positions|place_futures|close_futures|cancel_all_futures|Private exchange call blocked" logs/forward_paper.out 2>/dev/null; then
  echo "status=PRIVATE_CALL_MARKER_DETECTED"
  exit 6
fi

PYTHONPATH=. .venv/bin/python scripts/rebuild_forward_paper_outcomes.py >/dev/null

PYTHONPATH=. .venv/bin/python - <<'PY'
import csv
import json
from collections import Counter
from pathlib import Path

from forward_paper.store import ForwardPaperEventStore

events = ForwardPaperEventStore("data_store/forward_paper_events.jsonl").read_events()
with Path("data_store/forward_paper_outcomes.csv").open(encoding="utf-8", newline="") as handle:
    outcomes = list(csv.DictReader(handle))
quality = json.loads(Path("reports/forward_paper_data_quality.json").read_text(encoding="utf-8"))
event_types = Counter(event["event_type"] for event in events)
opened_ids = {event["trade_id"] for event in events if event["event_type"] == "TRADE_OPENED"}
closed_ids = {event["trade_id"] for event in events if event["event_type"] == "TRADE_CLOSED"}

if not quality.get("event_chain_valid"):
    raise SystemExit("status=INVALID_EVENT_CHAIN")
if quality.get("event_count") != len(events):
    raise SystemExit("status=QUALITY_EVENT_COUNT_MISMATCH")
if quality.get("complete_outcomes") != len(outcomes):
    raise SystemExit("status=QUALITY_OUTCOME_COUNT_MISMATCH")

print("event_chain=VALID")
print(f"events={len(events)}")
print(f"open_trades={len(opened_ids - closed_ids)}")
print(f"closed_trades={len(closed_ids)}")
print(f"outcomes={len(outcomes)}")
print(f"incomplete_trades={len(quality.get('incomplete_trades', []))}")
print("event_types=" + json.dumps(dict(sorted(event_types.items())), separators=(",", ":")))

heartbeat_path = Path("state/runtime_heartbeat.json")
if heartbeat_path.exists():
    heartbeat = json.loads(heartbeat_path.read_text(encoding="utf-8"))
    print("runtime_stage=" + str(heartbeat.get("stage") or "UNKNOWN"))
    print("scan_cycles_started=" + str(heartbeat.get("scan_cycles_started", 0)))
    print("scan_cycles_completed=" + str(heartbeat.get("scan_cycles_completed", 0)))
    print("runtime_ppid=" + str(heartbeat.get("ppid")))
    print("runtime_process_group=" + str(heartbeat.get("process_group")))
PY

echo "status=HEALTHY"
echo "mode=$MODE"
echo "pid=$PID"
echo "scan_interval_sec=$INTERVAL"
